- hosts: localhost
  roles:
  - role: aws

- hosts: controller
  roles:
  - role: controller

- hosts: workers
  roles:
  - role: worker     

- hosts: controller
  tasks:
  - shell:  "kubectl create deployment mywp --image=wordpress:5.1.1-php7.3-apache"   

  - shell: "kubectl run mydb --image=mysql:5.7  --env=MYSQL_USER=arpit  --env=MYSQL_PASSWORD=redhat --env=MYSQL_DATABASE=wpdb  --env=MYSQL_ROOT_PASSWORD=redhat"
    
  - shell: "kubectl expose deployment mywp --port 80 --type=NodePort"
  
  - name: "get service"
    shell: "kubectl get svc"
    register: service
  
  - debug:
      var: "service.stdout_lines" 
  
  - name: "Pausing playbook for 50 seconds"
    pause: 
      seconds: 50
  
  - name: "gettin database IP"
    shell: "kubectl get pods -o wide"
    register: Database
  
  - debug:
      var: "Database.stdout_lines"    
